name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.10"
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install poetry
  #         poetry install
  #     - name: Run tests
  #       run: poetry run pytest tests/

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install black flake8
      - name: Lint with Black
        run: black --check src/
      - name: Lint with Flake8
        run: flake8 src/

  # deploy:
  #   needs: [test, lint]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.10"
  #     - name: Install dependencies
  #       run: |
  #         pip install streamlit
  #     - name: Deploy to Streamlit
  #       env:
  #         STREAMLIT_TOKEN: ${{ secrets.STREAMLIT_TOKEN }}
  #       run: |
  #         echo "Deploying to Streamlit Cloud..."
  #         streamlit deploy app/main.py